### ISSUE TITLE
radian crashes on first time load of R.cache

### ISSUE THREAD

**Issue by renkun-ken** [randy3k/radian#143]
When R.cache is installed, and loaded for the first load, `radian` crashes on it promts to user asking where to put the cache directory.

<img width="872" alt="image" src="https://user-images.githubusercontent.com/4662568/74024112-17d9bd80-49dc-11ea-8aa2-4cd839bda59e.png">

**Comment by randy3k** [comment]
The error is triggered if a user do `R.cache::` while after installing `R.cache` (doing `library(R.cache)` is fine).

The root of the issue is that `R.cache` prompts while the package is loaded invisibly in the background (trigged by completions). `radian` does not expect any prompts in the `.onLoad` and `.onAttach` hooks of packages so it crashed.

The following is what we see in the ordinary R console:

```
> R.cache::The R.cache package needs to create a directory that will hold cache files. It is convenient to use  '/Users/Randy/Library/Caches/R/R.cache' because it follows the standard on your operating system and it remains also after restarting R. Do you wish to create the '/Users/Randy/Library/Caches/R/R.cache' directory? If not, a temporary directory (/var/folders/nz/8ncdbh01445fkwtvzj_71y8c0000gn/T//RtmpyNF5DX/.Rcache) that is specific to this R session will be used. [Y/n]:
```
