### ISSUE TITLE
Knitting RMarkdown Issue

### ISSUE THREAD

**Issue by YandLiu** [randy3k/radian#144]
I'm using Windows 10 x64, R 3.6.2 x64, Python 3.8.1 x64.
When I knitted this [RMarkdown](https://d3c33hcgiwev3.cloudfront.net/_43f5c1b4ef8358a74933caeb1853e914_sampling_distributions_Coursera.rmd?Expires=1581379200&Signature=FaqdaY-2XQF~Zgi0O5E3vFCEu~N8Qf62KlnCuqoI89Nl1DC~BIu2yRUgS4pXJpljMqrMj~qF6ryCfw0NyHjqU9HtsBK5-2t3EYmJfOvdDj683BkX0-l-AM-I2AzSSXZntGwV6uxqlGarCRvehC5UCxfTASuHU0Gv-eunxGEIrVk_&Key-Pair-Id=APKAJLTNE6QMUY6HBC5A) using radian, I found some symbols were added to the knitted HTML file comparing with knitting using native R.

Using Radian:
![radian](https://user-images.githubusercontent.com/26127104/74096937-af184f80-4b59-11ea-9c2e-8946eec48801.png)

Using R:
![r](https://user-images.githubusercontent.com/26127104/74096939-b2134000-4b59-11ea-8229-11c1ec0d4791.png)

**Comment by randy3k** [comment]
It was because we have enabled [crayon](https://github.com/r-lib/crayon) in default.

The reason was to enable certain color printing in the console. It seems that it has an side effect of enabling ansi color when using knitr. 

https://github.com/randy3k/radian/blob/master/radian/session.py#L62


A workaround for you now is to turn off crayon. Put the following in your .Rprople

```
options(crayon.enabled = FALSE)
```

**Comment by randy3k** [comment]
The current master version should fix it. Installing it by
```
pip install -U git+https://github.com/randy3k/radian
```
