### ISSUE TITLE
Improper indentation when using with neoterm

### ISSUE THREAD

**Issue by strboul** [randy3k/radian#173]
Hi @randy3k,

I've started using the [neoterm](https://github.com/kassio/neoterm) nvim plugin with *radian*.  I don't get the proper indentation on *radian* when I send new lines to the terminal via the `:TREPLSendLine` command of the neoterm.

The plugin solved a similar problem like this with ipython by calling it with `ipython --no-autoindent` (implementation [here](https://github.com/kassio/neoterm/blob/8a3a0fb0977d89b2f3533246f3238c0f48173e2e/ftdetect/set_repl_cmd.vim#L16)). Do you think we can have a similar parameter in *radian*, or the solution to this problem lies elsewhere?

The screenshot describes my problem:
![Screenshot 2020-04-19 at 21 33 38](https://user-images.githubusercontent.com/25015317/79697868-79909080-8285-11ea-9ec4-109fc1cd1849.png)

I have the following settings in my `init.vim`:

```vim
let g:neoterm_default_mod="belowright"
let g:neoterm_size=16
let g:neoterm_autoscroll=1
let g:neoterm_direct_open_repl=1
" Calling :Tclose or :Ttoggle kills the terminal
let g:neoterm_keep_term_open=0
" Set REPLs
if executable("radian")
  let g:neoterm_repl_r="radian"
endif
" send current line and move down
nnoremap <silent><leader><cr> :TREPLSendLine<cr>j
" send current selection
" ('> goes to the last selected Visual area in the current buffer)
vnoremap <silent><leader><cr> :TREPLSendSelection<cr>'>j
" toggle terminal
nnoremap <silent><c-t><c-t> :Ttoggle<CR>
tnoremap <silent><c-t><c-t> <C-\><C-n>:Ttoggle<CR>
```

I don't know if this problem is raised before. Thanks for the help!

**Comment by randy3k** [comment]
You basically need to enable bracketed paste mode in `TREPLSendSelection`. There was a PR on neoterm about that, but it is now staled.

https://github.com/kassio/neoterm/pull/234

**Comment by randy3k** [comment]
On the other hand, [Nvim-R](https://github.com/jalvesaq/Nvim-R) does support bracketed paste mode. https://github.com/randy3k/radian#nvim-r-support

**Comment by echasnovski** [comment]
Hello, @strboul and @randy3k!

I just created a [PR to 'neoterm'](https://github.com/kassio/neoterm/pull/296) which should enable bracketed paste mode. I tested it locally (Ubuntu and Gnome Terminal) and it works with both 'radian' and 'ipython'. Could you, please, give it a go so as to verify that it works on multiple setups.

Just in case. In order to install it if you are using vim-plug:

- Uninstall current version (remove/comment line `Plug 'kassio/neoterm'`, reopen Neovim, run `:PlugClean`).
- Install my PR fork (add `Plug 'echasnovski/neoterm', { 'branch': 'bracketed-paste' }`, run `:PlugInstall`).
- Enable bracketed paste option with `let g:neoterm_bracketed_paste = 1` somewhere in your Neovim setup (for example, in 'init.vim').
- To revert to original version, do the same but installing 'kassio/neoterm' instead.
