### ISSUE TITLE
received results from HIS_XPC_GetApplicationPolicyForURLs

### ISSUE THREAD

**Issue by hachepunto** [randy3k/radian#195]
Hi

Sometimes, after displaying many graphs and with the "Python.app" window open, the radian terminal starts sending this message over and over:

UpdateRecents: about to call HIS_XPC_GetApplicationPolicyForURLs with seed 2340020070
UpdateRecents: received results from HIS_XPC_GetApplicationPolicyForURLs
UpdateRecents: ignoring results because menu isn't open

The messages ends when the Python.app window is closed.

Thx for radian.

radian 0.5.4
Python 3.7.7
iTerm2 3.3.9
Mac OS Catalina 10.15.4

**Comment by randy3k** [comment]
I am quite sure it is not a radian specific issue. The plain R console should have the same issue. 

I used to get the same message and if I finally figured out that it was caused by a program called PopClip that was actively looking at the menu of my active application. You may want to check if a similar program is causing it.

**Comment by hachepunto** [comment]
That's right, I use Popclip. I tried to exclude iTerm from Popclip apps but it didn't work. But what did work was to exclude the Python.app app from Popclip. In my system it is here:

/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/Resources/Python.app

Messages no longer came out.

Thank you!

<img width="207" alt="Captura de Pantalla 7" src="https://user-images.githubusercontent.com/6043622/82916784-1bb43000-9f38-11ea-81ab-7c20b98061bf.png">
