### ISSUE TITLE
Plots display broken fonts

### ISSUE THREAD

**Issue by apoorvalal** [randy3k/radian#260]
running

```{r}
plot(rnorm(100), rnorm(100))
```
produces 
![image](https://user-images.githubusercontent.com/12086926/107889776-b212f200-6ec9-11eb-9ad8-b179b943df6a.png)

Running the same line in a regular R console produces a normal plot with correct fonts
![image](https://user-images.githubusercontent.com/12086926/107889797-d2db4780-6ec9-11eb-80ca-3613db349a6d.png)

I'm running R 4.0.3 + radian on Ubuntu 18.04.

**Comment by randy3k** [comment]
It was reported multiple times. But I really have no clue.

**Comment by randy3k** [comment]
Maybe related to fontconfig https://stackoverflow.com/questions/62031847/ggplot-axes-are-garbled-look-like-unicode-boxes

**Comment by zkamvar** [comment]
Thank you for pointing this out! I still have no clue how to implement the solution (partially because `${pkgs.fontconfig.out}` is not valid BASH, which means that there is a different tool being used here and the only blogs that I can find that even begin to describe what this is are in a language I do not understand), but this definitely brings me closer to understanding the issue.
