### ISSUE TITLE
Error when trying to use dplyr::mutate() in an RMarkdown (Rmd) file

### ISSUE THREAD

**Issue by adamroyjones** [randy3k/radian#85]
I am running:
* Ubuntu 16.04.5 LTS on an x86_64 platform,
* R 3.5.2 with dplyr 0.8.0.1 and tibble 2.0.1, and
* radian 0.3.1 on Python 3.7.2.

The following RMarkdown (Rmd) file...
````rmarkdown
---
title: "Minimal working example"
output:
  pdf_document:
    latex_engine: pdflatex
---

```{r}
library(tibble)
library(dplyr)

tbl = tribble(
  ~category, ~value,
  "a", 1,
  "a", 2,
  "b", 3,
  "b", 4)

tbl %>% mutate(category = toupper(category))
```
````
...does not compile when I attempt to render it from a radian session:
```
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Platform: x86_64-pc-linux-gnu (64-bit)

r$> rmarkdown::render("tmp.Rmd")                                                              


processing file: tmp.Rmd
  |................................                                 |  50%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-1
Quitting from lines 9-20 (tmp.Rmd) 
Error in mutate_impl(.data, dots, caller_env()) : 
  SET_VECTOR_ELT() can only be applied to a 'list', not a 'symbol'
```
The above function (`rmarkdown::render("tmp.Rmd")`) does, however, work when in an R session.

Do you have any ideas about what the issue is?

**Comment by randy3k** [comment]
I really don't have any idea. It is working on my machine by the way

```
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Platform: x86_64-apple-darwin15.6.0 (64-bit)

r$> rmarkdown::render("tmp.Rmd")


processing file: tmp.Rmd
  |................................                                 |  50%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-1

output file: tmp.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS tmp.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output tmp.tex --template /Users/Randy/Library/R/3.5/library/rmarkdown/rmd/latex/default-1.17.0.2.tex --highlight-style tango --pdf-engine pdflatex --variable graphics=yes --variable 'geometry:margin=1in' --variable 'compact-title:yes'

Output created: tmp.pdf

r$>
```

**Comment by docbiz** [comment]
Thanks for getting back to me so quickly!

The command likewise works on my Mac. I'm going to test it on another box of mine (running Ubuntu 18.04) as soon as I can configure it. (I hope this'll be within a few days.)

**Comment by R1V3RJ1s** [comment]
I replicate this issue with CentOS 6.10 on an x86_64 platform 
R 3.5.2 with dplyr 0.8.0(tidyselect_0.2.5) and tibble 2.1.1
radian 0.3.1 on Python 3.6.7

dplyr::select(df contains("id"))                                 
Error in select_impl(.data, vars) : 
  SET_VECTOR_ELT() can only be applied to a 'list', not a 'symbol'

However this could be run successfully with pure R

**Comment by docbiz** [comment]
This is just to confirm that I can reproduce the issue on my personal Ubuntu 18.04 box, as well (R 3.5.2, Python 3.7.2, radian 0.3.4, rmarkdown 1.11).

**Comment by randy3k** [comment]
I tried a docker image of R 3.5.2 from https://hub.docker.com/r/rocker/tidyverse/ and the Rmd above could be rendered just fine.

**Comment by docbiz** [comment]
Interesting! I'll try and write a Dockerfile that reproduces the problem so that it can be fully nailed down (e.g. maybe the base layer in the one you linked being Debian changes something). Hopefully I'll find the time over the next few days.

**Comment by docbiz** [comment]
I had a go tonight at constructing a Dockerfile to reproduce the problem, and possibly found a new problem—but it's quite probable that I have screwed something up.

```dockerfile
FROM ubuntu:18.04

RUN apt update -y

ENV TZ 'Europe/London'
RUN echo $TZ > /etc/timezone && \
    apt-get install -y tzdata && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

RUN apt install -y python3.7 python-pip

RUN apt install -y r-base

RUN apt install -y pandoc

RUN Rscript -e "install.packages(c('rmarkdown', 'dplyr', 'tibble'))"

RUN pip install radian

WORKDIR /app

COPY . /app
```
where the contents of `.` are the Dockerfile and the `tmp.Rmd` file described in the OP. I then run:
```bash
docker build --tag=radian-repex .
docker run -it radian-repex bash
radian
rmarkdown::render('tmp.Rmd')
```

This returned, for me:
```
r$> rmarkdown::render('tmp.Rmd')


processing file: tmp.Rmd
  |................................                                 |  50%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-1

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

🤷‍♂️

**Comment by randy3k** [comment]
it may be due to the same bug. Would you try the R from CRAN instead? I have a feeling that it is an issue of Ubuntu's R.

**Comment by docbiz** [comment]
I have a reproducing Dockerfile! 😄 

```Dockerfile
FROM rocker/r-base

RUN apt update

RUN apt install -y python3.7 python3-pip pandoc

RUN Rscript -e "install.packages(c('rmarkdown', 'dplyr', 'tibble'))"

RUN pip3 install radian

WORKDIR /app

COPY . /app
```

Then:
```bash
docker build --tag=rocker-r-repex .
docker run -it rocker-r-repex bash
radian
rmarkdown::render('tmp.Rmd')
```

The above yields:
```
root@9d315fcd8afe:/app# radian
R version 3.5.3 (2019-03-11) -- "Great Truth"
Platform: x86_64-pc-linux-gnu (64-bit)

r$> rmarkdown::render("tmp.Rmd")


processing file: tmp.Rmd
  |......................                                           |  33%
  ordinary text without R code

  |...........................................                      |  67%
label: unnamed-chunk-1
Quitting from lines 9-20 (tmp.Rmd)
Error in mutate_impl(.data, dots, caller_env()) :
  SET_VECTOR_ELT() can only be applied to a 'list', not a 'symbol'
```

Please let me know if this happens in your Docker environment, as well. (This was done in Docker 18.09.2 on a MacBook Pro.)

**Comment by randy3k** [comment]
Thank for it. Will play with it later today.

**Comment by cheneypinata** [comment]
Having the same issue with:

R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

In my case, I am coercing an adist() output to a numeric vector, into a column in a data frame, and then trying to arrange the data frame by that column.

I have never seen this error before, it's very odd.

**Comment by a-hurst** [comment]
Same issue with dplyr::summarize on my mac:

```
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6
```

The code causing the error is this:

```r
demos <- sat %>% group_by(participant) %>%
  summarize(age=first(age), gender=first(gender), handedness=first(handedness))
```

It happens regardless of whether I use piping, or just pass 'demos' directly as the first argument to summarize. If I comment out the 'summarize' line, the problem goes away. Likewise, if I run `rmarkdown::render` on the document in a regular R session, it happens without a problem. The only thing `first` is doing here is just grabbing the first element of passed dataframe, so I don't think there's any variable type coercion going on at all. It also happens regardless of whether I use "group_by" or not.

This error only happens when the code is run indirectly via `rmarkdown::render`, running it directly in a radian session works perfectly fine. Maybe it's something to do with the way the rmarkdown/knitr rendering process works?

**Comment by randy3k** [comment]
I still have no idea why and how it happens...

**Comment by a-hurst** [comment]
@randy3k I dug a bit more into this bug after I made my last post and *think* I have a rough idea of what's causing it, but pinpointing it exactly would probably require an in-depth knowledge of radian/rchitect that I don't really have.

Basically, it looks like it's due to the autocompletion code calling rchitect in a weird way that, if the radian session is new, breaks something in the R/Python communication for the remainder of the session. The evidence for this comes from my own experimentation, which is hopefully reproducible on your setup:

1. Open a new radian session

2. Start typing `rmarkdown::`, but when the autocomplete pops up, hit the down arrow and hit enter to select the suggestion.

3. Delete the contents of the line without running it, then run 

```r
library(dplyr)
data(mtcars)
eval(parse(text = "mtcars %>% group_by(cyl) %>% summarize(mpg= mean(mpg))"))
```

You should get the `Error in summarise_impl(.data, dots, environment(), caller_env()) :
  SET_VECTOR_ELT() can only be applied to a 'list', not a 'symbol'` error.


However, if you do the exact same steps but *don't* choose the autocomplete option, the dplyr code reliably runs fine. Also, if you do the exact same sequence of steps but load a library first (e.g. `library(tidyr)`), the dplyr code also runs fine. If I had to guess, I'd say it's probably the selection of the autocomplete suggestion interrupting an rchitect/R call related to initialization in some way that disrupts the processing of vectors.

Hope that helps with a fix!

**Comment by Peder2911** [comment]
Hey! This error keeps popping up for me:
`Error in select_impl(.data, vars) : 
  SET_VECTOR_ELT() can only be applied to a 'list', not a 'symbol'`
In this case, i tried to plot a DAG from the package dagitty with ggdag.

**Comment by Peder2911** [comment]
I have also seen it elsewhere, but i can't remember what i called.
In both cases (then and now), the command runs fine in a regular R repl.

**Comment by randy3k** [comment]
@a-hurst

Thank you for your example. I would reproduce it now. Let'me if see if I could understand why it happens.

**Comment by randy3k** [comment]
Looks like, it is caused by the timeout in `utils:::.completeToken` when we are getting completions from the command line.

We are doing something like this
```r
base::setTimeLimit(timeout)
utils:::.completeToken()
base::setTimeLimit(0)
```
But it seems that while loading the completions from `rmarkdown`, canceling completions will leave it in an unclean state and (perhaps some variables are not cleaned? not sure). Eventually, `dplyr` picked up a wrong variable when caused the error. Disabling the timeout seems to fix the issue.

```
options(radian_completion_timeout = 0)
```

**Comment by randy3k** [comment]
7700907 has increased the default timeout, it should fix the issue for most users. I'll need to dig further to investigate the exact cause.

**Comment by randy3k** [comment]
I updated dplyr to 0.8.3 and I could no longer reproduce the bug...

**Comment by adamroyjones** [comment]
Just to add: I likewise cannot reproduce this. Thanks for looking into this—and for all of your work on radian.
